# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with: 
        lfs: true
    - name: checkout lfs object
      run: git lfs checkout
    - name: Build test
      uses: pguyot/arm-runner-action@v2.5.1
      id: Build-Python-exe
      with:
        image_additional_mb: 3584
        copy_repository_path: /home/pi
        copy_artifact_path: CSEE8300_Project/exampleCode/dist/algo_VTCN
        base_image: raspios_lite_arm64:latest
        commands: |
            sudo apt-get update -y;
            pwd;
            apt-get install -y python3 python3-venv python3-dev python3-pip;
            cd CSEE8300_Project/ ;
            pip3 install -r requirements;
            cd exampleCode;
            pyinstaller --clean --onefile algo_VTCN.py;
    - uses: actions/upload-artifact@v3
      with:
        name: exe_file
        path: algo_VTCN
        if-no-files-found: error
        retention-days: 3


    # - run: echo "${{ steps.Build-Python-exe.outputs.image }}"
    # - run: ls -a
    # - run: pwd
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: exe_file
    #     path: hello
    #     if-no-files-found: error
    #     retention-days: 3
    # - name: Compress the release image
    #   run: |
    #     sudo xz -T 0 -v ${{ steps.Build-Python-exe.outputs.image }}
    # - name: Upload the image artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: build_image
    #     path: ${{ steps.Build-Python-exe.outputs.image }}.xz
    #     if-no-files-found: error
    #     retention-days: 10

  upload:
    runs-on: raspi
    needs: build
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: exe_file
      - run: cp algo_VTCN /home/pi/
      - run: cd /home/pi
      - run: chmod +x algo_VTCN
      - run: ./algo_VTCN --label_name=S --dropout=0.1 --train=10min_train.npy --test=10min_test.npy
      # - run: chmod +x algo_VTCN
      # - run: ./algo_VTCN --label_name=S --dropout=0.1 --train=10min_train.npy --test=10min_test.npy
    #  - run: scp README.md pi@192.168.0.67:~ 
    #   - run: ssh pi@192.168.0.67
    #   - run: chmod +x algo_VTCN 
      # - run: ./algo_VTCN 


        # commands: |
        #     sudo apt-get update -y;
        #     pwd;
        #     apt-get install -y python3 python3-venv python3-dev python3-pip;
        #     pip3 install torch;
        #     pip3 install --upgrade pip;
        #     pip3 install numpy --upgrade;
        #     pip3 install -U scikit-learn;
        #     pip3 install -U matplotlib;
        #     pip3 install pyinstaller;
        #     pip3 install nvidia-ml-py3
        #     cd /home/pi/;
        #     ls -a;
        #     cd CSEE8300_Project/exampleCode;
        #     pyinstaller --clean --onefile algo_VTCN.py;
        #     ls -a;
        #     cd dist;
        #     ls -a;

        # commands: |
        #     sudo apt-get update -y;
        #     pwd;
        #     apt-get install -y python3 python3-venv python3-dev python3-pip;
        #     cd /home/pi/;
        #     ls -a;
        #     cd CSEE8300_Project/exampleCode;
        #     pyinstaller --clean --onefile hello.py;