# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build test
      uses: pguyot/arm-runner-action@v2.4.0
      id: Build-Python-exe
      with:
        image_additional_mb: 3584
        copy_repository_path: /home/pi/pynab
        commands: |
            sudo apt-get update -y
            sudo apt-get install -y python3 python3-venv python3-dev python3-pip
            sudo pip3 install --upgrade pip
            sudo pip3 install pyinstaller
