name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  file_to_build: algo_VTCN.py #file you want to build
  pi_image: raspios_lite_arm64:latest #image you want to use need 64 bit image for pytorch
  path_to_file: CSEE8300_Project/exampleCode #folder that $file_to_build is in
  built_file_name: algo_VTCN #name of the built file


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo #checkout code so most up-to-date version is accessible to the runner
      uses: actions/checkout@main
      with: 
        lfs: true #lfs is github large file storage system
    - name: checkout lfs object
      run: git lfs checkout
    - name: Build test
      uses: pguyot/arm-runner-action@main #this action emulates an ARM CPU and a desired operating system $pi_image
      id: Build-Python-exe
      with:
        image_additional_mb: 3584
        copy_repository_path: /home/pi
        copy_artifact_path: ${{env.path_to_file}}/dist/${{env.built_file_name}}
        base_image: ${{env.pi_image}}
        commands: |
            sudo apt-get update -y;
            pwd;
            apt-get install -y python3 python3-venv python3-dev python3-pip; 
            cd ${{env.path_to_file}};
            pip3 install torch;
            pip3 install --upgrade pip;
            pip3 install numpy --upgrade;
            pip3 install -U scikit-learn;
            pip3 install -U matplotlib;
            pip3 install pyinstaller;
            pip3 install nvidia-ml-py3
            pyinstaller --clean --onefile ${{env.file_to_build}};
    - uses: actions/upload-artifact@main
      with:
        name: exe_file
        path: ${{env.built_file_name}}
        if-no-files-found: error
        retention-days: 3


    # - run: echo "${{ steps.Build-Python-exe.outputs.image }}"
    # - run: ls -a
    # - run: pwd
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: exe_file
    #     path: hello
    #     if-no-files-found: error
    #     retention-days: 3
    # - name: Compress the release image
    #   run: |
    #     sudo xz -T 0 -v ${{ steps.Build-Python-exe.outputs.image }}
    # - name: Upload the image artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: build_image
    #     path: ${{ steps.Build-Python-exe.outputs.image }}.xz
    #     if-no-files-found: error
    #     retention-days: 10

  upload:
    runs-on: raspi
    needs: build
    steps: 
      - name: Checkout repo
        uses: actions/checkout@main
      - uses: actions/download-artifact@main
        with:
          name: exe_file
      - run: cp ${{env.built_file_name}} /home/pi/
      - run: cd /home/pi
      - run: chmod +x ${{env.built_file_name}}
      - run: ./${{env.built_file_name}} --label_name=S --dropout=0.1 --train=10min_train.npy --test=10min_test.npy
      # - run: chmod +x algo_VTCN
      # - run: ./algo_VTCN --label_name=S --dropout=0.1 --train=10min_train.npy --test=10min_test.npy
    #  - run: scp README.md pi@192.168.0.67:~ 
    #   - run: ssh pi@192.168.0.67
    #   - run: chmod +x algo_VTCN 
      # - run: ./algo_VTCN 


        # commands: |
        #     sudo apt-get update -y;
        #     pwd;
        #     apt-get install -y python3 python3-venv python3-dev python3-pip;
        #     pip3 install torch;
        #     pip3 install --upgrade pip;
        #     pip3 install numpy --upgrade;
        #     pip3 install -U scikit-learn;
        #     pip3 install -U matplotlib;
        #     pip3 install pyinstaller;
        #     pip3 install nvidia-ml-py3
        #     cd /home/pi/;
        #     ls -a;
        #     cd CSEE8300_Project/exampleCode;
        #     pyinstaller --clean --onefile algo_VTCN.py;
        #     ls -a;
        #     cd dist;
        #     ls -a;

        # commands: |
        #     sudo apt-get update -y;
        #     pwd;
        #     apt-get install -y python3 python3-venv python3-dev python3-pip;
        #     cd /home/pi/;
        #     ls -a;
        #     cd CSEE8300_Project/exampleCode;
        #     pyinstaller --clean --onefile hello.py;