# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: checkout lfs object
      run: git lfs checkout
    - name: Build test
      uses: pguyot/arm-runner-action@v2.4.0
      id: Build-Python-exe
      with:
        image_additional_mb: 3584
        copy_repository_path: /home/pi
        commands: |
            sudo apt-get update -y
            pwd
            sudo apt-get install -y python3 python3-venv python3-dev python3-pip
            sudo pip3 install --upgrade pip
            sudo pip3 install pyinstaller
            cd /home/pi/
            ls -a
            cd CSEE8300_Project/exampleCode
            pyinstaller --clean --onefile algo_VTCN.py
            ls -a
            cd dist
            ls -a
    - run: echo "${{ steps.build-python-exe.outputs.image }}"
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: my-artifact
    #     path: 