# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: checkout lfs object
      run: git lfs checkout
    - name: Build test
      uses: pguyot/arm-runner-action@v2.5.1
      id: Build-Python-exe
      with:
        image_additional_mb: 3584
        copy_repository_path: /home/pi
        copy_artifact_path: CSEE8300_Project/exampleCode/dist/algo_VTCN
        commands: |
            sudo apt-get update -y;
            pwd;
            sudo apt-get install -y python3 python3-venv python3-dev python3-pip;
            sudo pip3 install --upgrade pip;
            sudo pip3 install -f torch 
            sudo pip3 install torchvision
            sudo pip3 install numpy
            sudo pip3 install nvidia-ml-py3
            sudo pip3 install -U scikit-learn
            sudo pip3 install pyinstaller;
            cd /home/pi/;
            ls -a;
            cd CSEE8300_Project/exampleCode;
            pyinstaller --clean --onefile algo_VTCN.py;
            ls -a;
            cd dist;
            ls -a;

    - run: echo "${{ steps.Build-Python-exe.outputs.image }}"
    - run: ls -a
    - run: pwd
    - uses: actions/upload-artifact@v3
      with:
        name: exe_file
        path: algo_VTCN
        if-no-files-found: error
        retention-days: 10

    # - name: Compress the release image
    #   run: |
    #     sudo xz -T 0 -v ${{ steps.Build-Python-exe.outputs.image }}
    # - name: Upload the image artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: build_image
    #     path: ${{ steps.Build-Python-exe.outputs.image }}.xz
    #     if-no-files-found: error
    #     retention-days: 10
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: my-artifact
    #     path: 